# Generated by Django 4.0.5 on 2022-07-07 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.TextField()),
                ('password', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('comentario', models.TextField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comentarios.usuario', verbose_name='Marca')),
            ],
        ),
    ]
