# Generated by Django 4.0.5 on 2022-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_remove_comentario_marca_comentario_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagenesdeperfil',
            field=models.ImageField(null=True, upload_to='usuarios', verbose_name='Fotografía'),
        ),
    ]
