# Generated by Django 4.0.5 on 2022-07-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_usuario_imagenesdeperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.TextField()),
                ('password', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('imagenesdeperfil', models.ImageField(null=True, upload_to='usuarios', verbose_name='Fotografía')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
