# Generated by Django 4.0.5 on 2022-08-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_remove_user_imagenesdeperfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Useres'},
        ),
    ]
