# Generated by Django 4.0.5 on 2022-08-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0007_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.CharField(max_length=10)),
                ('comentario', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Coment',
                'verbose_name_plural': 'Coments',
            },
        ),
    ]
