# Generated by Django 4.0.5 on 2022-08-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0008_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
