# Generated by Django 4.0.5 on 2022-08-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proye', '0001_initial'),
        ('comentarios', '0009_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proye.productos', verbose_name='Productos'),
        ),
    ]
