# Generated by Django 4.0.5 on 2022-07-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('catego', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('edad', models.CharField(max_length=20)),
                ('rangoedad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('material', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('destacado', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoj.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoj.marca', verbose_name='Marca')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoj.material', verbose_name='Material')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='rangoedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoj.edad', verbose_name='Rango de edad'),
        ),
    ]
