# Generated by Django 4.0.5 on 2022-07-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='material',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Edad',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
