# Generated by Django 4.0.5 on 2022-07-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('catego', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('edad', models.CharField(max_length=20)),
                ('rangoedad', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Edad',
                'verbose_name_plural': 'Edades',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('marca', models.CharField(max_length=20)),
                ('imagenmarca', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('grupo', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('material', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('destacado', models.BooleanField()),
                ('grupo', models.IntegerField(default=1)),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proye.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proye.marca', verbose_name='Marca')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proye.material', verbose_name='Material')),
                ('rangoedad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proye.edad', verbose_name='Rango de edad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='rangoedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proye.edad', verbose_name='Rango de edad'),
        ),
    ]
